version: '3'
services:
  influxdb:
    image: hypriot/rpi-influxdb
    ports:
      - 8086:8086
    volumes:
      - ./influxdb:/data
    environment:
      ADMIN_USER: "root"
      INFLUXDB_INIT_PWD: "root"
      PRE_CREATE_DB: "climatedata"

  grafana:
    image: fg2it/grafana-armhf
    ports:
      - 3000:3000
  tempmonitor:
    build: .
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    links:
      - influxdb
    environment:
      INFLUXDB_HOST: "influxdb"
      INFLUXDB_PORT: "8086"
      INFLUXDB_USER: "root"
      INFLUXDB_PASSWORD: "root"
      INFLUXDB_DBNAME: "climatedata"


